#! /usr/bin/sh

mkdir -p masterdir/sources masterdir/builddir masterdir/destdir

check_utils() {
    broken=0
    for f in ${REQ_UTILS}; do
        if ! command -v "${f}" >/dev/null 2>&1; then
            echo "${f} is missing in your system, can't continue!" 1>&2
            broken=1
        fi
    done
    [ "$broken" -eq 1 ] && exit 1
    return 0
}

readonly REQ_UTILS="curl sha256sum mutool python3 pdftocairo"
check_utils

if [ "$2" ]; then
    TARGET_DOC="$2"
fi

. "$TARGET_DOC/template"

cd masterdir

if [ ! -f "sources/original.pdf" ]; then
    . ../common/do_fetch
fi

if [ "$1" = "fetch" ]; then
    exit 0
fi
. ../common/do_clean
. ../common/do_patch
. ../common/do_visual_diff || exit $?
. ../common/do_optimize

# Move final PDF to destination directory
mv "builddir/final.pdf" "destdir/${author} - ${title}.pdf"

