#! /usr/bin/sh
title="Rational points on modular elliptic curves"
author="Henri Darmon"
url="https://www.math.mcgill.ca/darmon/pub/Articles/Research/36.NSF-CBMS/chapter.pdf"
checksum="04f00c11cbb6767753a7f1509273dc81e8dc7950c88873a5d930d90e93d7b873"

mkdir build
cd build
wget $url --output-document=original.pdf
cksum=$(sha256sum original.pdf | cut -d ' ' -f 1)
if [ "$cksum" != "$checksum" ]; then
    echo "Error: Checksum mismatch"
    echo "$cksum"
    exit 1
fi
mutool clean -dg original.pdf cleaned.pdf
patch -u  cleaned.pdf ../patches/*.patch
qpdf --stream-data=compress cleaned.pdf "${author} - ${title}.pdf"


